### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by HaleTom** [supriyo-biswas/static-builds#1]
Hi, would you consider building rsync?  It's an extremely useful util, and SFTP doesn't work without it.

Cheers!
Tom

**Comment by HaleTom** [comment]
https://github.com/jbruechert/rsync-static/blob/master/build_static.sh

**Comment by HaleTom** [comment]
Perhaps these would help, too:
https://github.com/walthowd/rsync-static/blob/main/Dockerfile
https://github.com/hboetes/build_static_rsync/blob/main/generate-rsync-static

**Comment by supriyo-biswas** [comment]
This request has been accepted, though I will work on adding rsync as my time allows for.

I believe you’re mistaken in saying rsync requires sftp; but what is more concerning is that the sftp binaries in the last release have hardcoded paths preventing them from working as expected. I’ve created a separate issue for this (#2)

**Comment by supriyo-biswas** [comment]
`rsync` is now available.
https://github.com/supriyo-biswas/static-builds/releases/tag/rsync-3.3.0

Additionally, the OpenSSH issues should also be fixed.
Please feel free to test the binaries and report issues, if any.
